version: '3.7'
services:
  mlflow:
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    #user: "1000:1000"
    build: 
      context: ./mlflow
      dockerfile: Dockerfile
    network_mode: host
    image: mlflow-server
    container_name: mlflow
    command: >-
      sh -c "umask 0000 && mkdir -p ${MLDATA} && 
      mlflow server --backend-store-uri ${MLDATA} --host 0.0.0.0 
      --default-artifact-root ${MLDATA}"
    ports:
      - "5000:5000"
    volumes:
     - /tmp/ltex/:/tmp/ltex/
